# docker-compose.yml
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
    # sslmode=disable is only for local development without SSL
      - DB_SOURCE=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable 
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
    